// <auto-generated />
using System;
using Elbrus.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Elbrus.Migrations
{
    [DbContext(typeof(DiplomContext))]
    [Migration("20260516155644_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Elbrus.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Address")
                        .HasColumnType("character varying")
                        .HasColumnName("address");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<int?>("ClientCode")
                        .HasColumnType("integer")
                        .HasColumnName("client_code");

                    b.Property<string>("Email")
                        .HasColumnType("character varying")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasColumnType("character varying")
                        .HasColumnName("full_name");

                    b.Property<string>("Passport")
                        .HasColumnType("character varying")
                        .HasColumnName("passport");

                    b.Property<string>("Password")
                        .HasColumnType("character varying")
                        .HasColumnName("password");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("ClientId")
                        .HasName("client_pkey");

                    b.HasIndex("RoleId");

                    b.ToTable("client", (string)null);
                });

            modelBuilder.Entity("Elbrus.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeId"));

                    b.Property<int?>("EnterStatus")
                        .HasColumnType("integer")
                        .HasColumnName("enter_status");

                    b.Property<string>("FullName")
                        .HasColumnType("character varying")
                        .HasColumnName("full_name");

                    b.Property<DateTime?>("LastEnter")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_enter");

                    b.Property<string>("Login")
                        .HasColumnType("character varying")
                        .HasColumnName("login");

                    b.Property<string>("Passwrd")
                        .HasColumnType("character varying")
                        .HasColumnName("passwrd");

                    b.Property<string>("Photo")
                        .HasColumnType("character varying")
                        .HasColumnName("photo");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("EmployeeId")
                        .HasName("employee_pkey");

                    b.HasIndex("EnterStatus");

                    b.HasIndex("RoleId");

                    b.ToTable("employee", (string)null);
                });

            modelBuilder.Entity("Elbrus.Models.EnterStatus", b =>
                {
                    b.Property<int>("EnterStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("enter_status_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EnterStatusId"));

                    b.Property<string>("EnterStatusName")
                        .HasColumnType("character varying")
                        .HasColumnName("enter_status_name");

                    b.HasKey("EnterStatusId")
                        .HasName("enter_status_pkey");

                    b.ToTable("enter_status", (string)null);
                });

            modelBuilder.Entity("Elbrus.Models.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("inventory_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InventoryId"));

                    b.Property<string>("InventoryModel")
                        .HasColumnType("character varying")
                        .HasColumnName("inventory_model");

                    b.Property<string>("InventoryName")
                        .HasColumnType("character varying")
                        .HasColumnName("inventory_name");

                    b.Property<string>("Photo")
                        .HasColumnType("character varying")
                        .HasColumnName("photo");

                    b.Property<int?>("RentalCostPerHour")
                        .HasColumnType("integer")
                        .HasColumnName("rental_cost_per_hour");

                    b.HasKey("InventoryId")
                        .HasName("inventory_pkey");

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("Elbrus.Models.InventoryItem", b =>
                {
                    b.Property<int>("InventoryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("inventory_item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InventoryItemId"));

                    b.Property<int>("InventoryId")
                        .HasColumnType("integer")
                        .HasColumnName("inventory_id");

                    b.Property<string>("InventoryNumber")
                        .HasColumnType("character varying")
                        .HasColumnName("inventory_number");

                    b.Property<int?>("InventoryStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("inventory_status_id");

                    b.Property<string>("Size")
                        .HasColumnType("character varying")
                        .HasColumnName("size");

                    b.HasKey("InventoryItemId")
                        .HasName("inventory_item_pkey");

                    b.HasIndex("InventoryId");

                    b.HasIndex("InventoryStatusId");

                    b.ToTable("inventory_item", (string)null);
                });

            modelBuilder.Entity("Elbrus.Models.InventoryStatus", b =>
                {
                    b.Property<int>("InventoryStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("inventory_status_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InventoryStatusId"));

                    b.Property<string>("InventoryStatusName")
                        .HasColumnType("character varying")
                        .HasColumnName("inventory_status_name");

                    b.HasKey("InventoryStatusId")
                        .HasName("inventory_status_pkey");

                    b.ToTable("inventory_status", (string)null);
                });

            modelBuilder.Entity("Elbrus.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateOnly?>("DateCreate")
                        .HasColumnType("date")
                        .HasColumnName("date_create");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<string>("OrderCode")
                        .HasColumnType("character varying")
                        .HasColumnName("order_code");

                    b.Property<TimeOnly?>("TimeCreate")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_create");

                    b.Property<int?>("TotalPrice")
                        .HasColumnType("integer")
                        .HasColumnName("total_price");

                    b.HasKey("OrderId")
                        .HasName("order_pkey");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("order", (string)null);
                });

            modelBuilder.Entity("Elbrus.Models.OrderInventory", b =>
                {
                    b.Property<int>("OrderInventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("order_inventory_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderInventoryId"));

                    b.Property<int?>("InventoryItemId")
                        .HasColumnType("integer")
                        .HasColumnName("inventory_item_id");

                    b.Property<int?>("OrderServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("order_service_id");

                    b.Property<int?>("RentTime")
                        .HasColumnType("integer")
                        .HasColumnName("rent_time");

                    b.HasKey("OrderInventoryId")
                        .HasName("order_inventory_pkey");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("OrderServiceId");

                    b.ToTable("order_inventory", (string)null);
                });

            modelBuilder.Entity("Elbrus.Models.OrderService", b =>
                {
                    b.Property<int>("OrderServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("order_service_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderServiceId"));

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int?>("OrderStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("order_status_id");

                    b.Property<int?>("RentTime")
                        .HasColumnType("integer")
                        .HasColumnName("rent_time");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.Property<TimeOnly?>("TimeIn")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_in");

                    b.Property<TimeOnly?>("TimeOut")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_out");

                    b.HasKey("OrderServiceId")
                        .HasName("order_service_pkey");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("ServiceId");

                    b.ToTable("order_service", (string)null);
                });

            modelBuilder.Entity("Elbrus.Models.OrderStatus", b =>
                {
                    b.Property<int>("OrderStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("order_status_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderStatusId"));

                    b.Property<string>("OrderStatusName")
                        .HasColumnType("character varying")
                        .HasColumnName("order_status_name");

                    b.HasKey("OrderStatusId")
                        .HasName("order_status_pkey");

                    b.ToTable("order_status", (string)null);
                });

            modelBuilder.Entity("Elbrus.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .HasColumnType("character varying")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("role_pkey");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("Elbrus.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServiceId"));

                    b.Property<int?>("CostPerHour")
                        .HasColumnType("integer")
                        .HasColumnName("cost_per_hour");

                    b.Property<string>("ServiceCode")
                        .HasColumnType("character varying")
                        .HasColumnName("service_code");

                    b.Property<string>("ServiceName")
                        .HasColumnType("character varying")
                        .HasColumnName("service_name");

                    b.HasKey("ServiceId")
                        .HasName("service_pkey");

                    b.ToTable("service", (string)null);
                });

            modelBuilder.Entity("Elbrus.Models.Client", b =>
                {
                    b.HasOne("Elbrus.Models.Role", "Role")
                        .WithMany("Clients")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("client_role_id_fkey");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Elbrus.Models.Employee", b =>
                {
                    b.HasOne("Elbrus.Models.EnterStatus", "EnterStatusNavigation")
                        .WithMany("Employees")
                        .HasForeignKey("EnterStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("employee_enter_status_fkey");

                    b.HasOne("Elbrus.Models.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("employee_role_id_fkey");

                    b.Navigation("EnterStatusNavigation");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Elbrus.Models.InventoryItem", b =>
                {
                    b.HasOne("Elbrus.Models.Inventory", "Inventory")
                        .WithMany("InventoryItems")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("inventory_item_inventory_id_fkey");

                    b.HasOne("Elbrus.Models.InventoryStatus", "InventoryStatus")
                        .WithMany("InventoryItems")
                        .HasForeignKey("InventoryStatusId");

                    b.Navigation("Inventory");

                    b.Navigation("InventoryStatus");
                });

            modelBuilder.Entity("Elbrus.Models.Order", b =>
                {
                    b.HasOne("Elbrus.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("order_client_id_fkey");

                    b.HasOne("Elbrus.Models.Employee", "Employee")
                        .WithMany("Orders")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("order_employee_id_fkey");

                    b.Navigation("Client");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Elbrus.Models.OrderInventory", b =>
                {
                    b.HasOne("Elbrus.Models.InventoryItem", "InventoryItem")
                        .WithMany("OrderInventories")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("order_inventory_inventory_item_id_fkey");

                    b.HasOne("Elbrus.Models.OrderService", "OrderService")
                        .WithMany("OrderInventories")
                        .HasForeignKey("OrderServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("order_inventory_order_service_id_fkey");

                    b.Navigation("InventoryItem");

                    b.Navigation("OrderService");
                });

            modelBuilder.Entity("Elbrus.Models.OrderService", b =>
                {
                    b.HasOne("Elbrus.Models.Order", "Order")
                        .WithMany("OrderServices")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("order_service_order_id_fkey");

                    b.HasOne("Elbrus.Models.OrderStatus", "OrderStatus")
                        .WithMany("OrderServices")
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("order_service_order_status_id_fkey");

                    b.HasOne("Elbrus.Models.Service", "Service")
                        .WithMany("OrderServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("order_service_service_id_fkey");

                    b.Navigation("Order");

                    b.Navigation("OrderStatus");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Elbrus.Models.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Elbrus.Models.Employee", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Elbrus.Models.EnterStatus", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Elbrus.Models.Inventory", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("Elbrus.Models.InventoryItem", b =>
                {
                    b.Navigation("OrderInventories");
                });

            modelBuilder.Entity("Elbrus.Models.InventoryStatus", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("Elbrus.Models.Order", b =>
                {
                    b.Navigation("OrderServices");
                });

            modelBuilder.Entity("Elbrus.Models.OrderService", b =>
                {
                    b.Navigation("OrderInventories");
                });

            modelBuilder.Entity("Elbrus.Models.OrderStatus", b =>
                {
                    b.Navigation("OrderServices");
                });

            modelBuilder.Entity("Elbrus.Models.Role", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Elbrus.Models.Service", b =>
                {
                    b.Navigation("OrderServices");
                });
#pragma warning restore 612, 618
        }
    }
}
